# Generated by Django 3.2.6 on 2021-09-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='id_absensi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.mastersiswa'),
        ),
    ]
