# Generated by Django 3.2.6 on 2021-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_absensi_id_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='id_absensi',
            field=models.CharField(max_length=100),
        ),
    ]
